# Generated by Django 5.1.4 on 2024-12-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teaching.student'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teaching.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.skill'),
        ),
        migrations.AddField(
            model_name='teacherskill',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('teacher_profile', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherskill',
            unique_together={('teacher_profile', 'skill')},
        ),
    ]
